### ISSUE TITLE
One tracker displays double the amount of the actual.

### ISSUE THREAD

**Issue by Pro-Z-Emil** [mikabytes/gearbox#14]
![image](https://github.com/mikabytes/gearbox/assets/165383378/74ac3505-01fe-47bb-876a-44058d078318)

**Comment by Pro-Z-Emil** [comment]
Solved :)

**Comment by mikabytes** [comment]
Thanks for reporting this! 

Fixed in https://github.com/mikabytes/gearbox/commit/e47371a0344b2d9485037ca76efa1d85a84f02e7
