### ISSUE TITLE
Set torrent location

### ISSUE THREAD

**Issue by mikabytes** [mikabytes/gearbox#19]
- Add shortcut (research what shortcuts other clients are using, add as many as feasable)
- Context-menu option

**Comment by adia** [comment]
Transmission-web uses Ctrl-L for this, but personally I don't like it much since this shortcut normally focuses the browser location bar.

In any case, changing the location should be possible to apply to many selected torrents at once.

**Comment by mikabytes** [comment]
Hi Adia, 

Good input!

We could go with Ctrl-L as a default, with an option to change it. I anyway want to add a settings screen eventually so we don't need to change config files.

And yeah, it should work on every selected file. 

Both Transmission and Deluge have issues moving data. The client tends to freeze up. It might be interesting to look into some means of pre-copying data before issuing a move, and then deleting source data. Probably out of scope for this issue though. Let's get something working quickly, then create new issues for deeper integration.
