### ISSUE TITLE
Display "Error" section more prominently in the sidebar?

### ISSUE THREAD

**Issue by adia** [mikabytes/gearbox#30]
Since the "Tracker" section might contain a lot of entries, the "Error" section is usually hidden at the bottom. Since the errors might require attention, perhaps they should appear second, just under "Status", so that they are immediately visible?

**Comment by mikabytes** [comment]
That's a good point. I probably didn't notice because I have a very big screen. I was thinking of working on #26 next, and there it would become more apparent.

Placing it just under "status" sounds good to me.

**Comment by mikabytes** [comment]
Keep the ideas coming :partying_face:
