### ISSUE TITLE
Error message when adding 1,5 TB torrent

### ISSUE THREAD

**Issue by Pro-Z-Emil** [mikabytes/gearbox#36]
I get this error message when I try to add a 1,5 TB torrent.
The .torrent file is 1930 kB.
![image](https://github.com/mikabytes/gearbox/assets/165383378/f1fa93bb-ab7f-4547-942b-51ab455fda13)

**Comment by mikabytes** [comment]
That is odd. I've set the limit at 10mb, which is more than the 1930kb .torrent file. 

I'll have to investigate.

**Comment by adia** [comment]
If you look closely, the error is produced by nginx and not by Gearbox - you have it behind a reverse proxy, right?

You probably need to put `client_max_body_size 10M;` somewhere in your nginx config.

**Comment by mikabytes** [comment]
Ah, yes!

@Pro-Z-Emil As you are using Nginx Ingress, you can follow [instructions here](https://stackoverflow.com/questions/49918313/413-error-with-kubernetes-and-nginx-ingress-controller)

Probably, adding this annotation: 

```
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
```
